#!/usr/bin/env python
from livereload.task import Task
from livereload.compiler import shell

# Task.add('.[^_build/]', shell('make html'))
Task.add('*.rst', shell('make html'))
Task.add('afolder/*.rst', shell('make html'))
